/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ywb9yUr4YBN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover"
import { Calendar } from "@/components/ui/calendar"
import { Separator } from "@/components/ui/separator"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"

export function NewBooking2() {
  return (
    (<div
      className="w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16 lg:py-20">
      <div className="grid grid-cols-1 md:grid-cols-12 gap-8">
        <div className="md:col-span-8">
          <h1 className="text-3xl font-bold tracking-tight mb-4">New Booking Process</h1>
          <div className="bg-card rounded-lg shadow-lg overflow-hidden">
            <div
              className="bg-primary-foreground text-primary-background px-6 py-4 font-medium">
              Step 1: Select Car
            </div>
            <div className="p-6 space-y-6">
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
                <div className="bg-muted rounded-lg p-4 space-y-2">
                  <img
                    src="/placeholder.svg"
                    width={300}
                    height={200}
                    alt="Car Model"
                    className="rounded-lg"
                    style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                  <div className="font-medium">Toyota Camry</div>
                  <div className="text-muted-foreground text-sm">Midsize Sedan</div>
                  <div className="flex items-center justify-between">
                    <div className="font-medium">$50/day</div>
                    <Button size="sm">Select</Button>
                  </div>
                </div>
                <div className="bg-muted rounded-lg p-4 space-y-2">
                  <img
                    src="/placeholder.svg"
                    width={300}
                    height={200}
                    alt="Car Model"
                    className="rounded-lg"
                    style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                  <div className="font-medium">Honda Civic</div>
                  <div className="text-muted-foreground text-sm">Compact Sedan</div>
                  <div className="flex items-center justify-between">
                    <div className="font-medium">$40/day</div>
                    <Button size="sm">Select</Button>
                  </div>
                </div>
                <div className="bg-muted rounded-lg p-4 space-y-2">
                  <img
                    src="/placeholder.svg"
                    width={300}
                    height={200}
                    alt="Car Model"
                    className="rounded-lg"
                    style={{ aspectRatio: "300/200", objectFit: "cover" }} />
                  <div className="font-medium">Ford F-150</div>
                  <div className="text-muted-foreground text-sm">Full-Size Pickup</div>
                  <div className="flex items-center justify-between">
                    <div className="font-medium">$70/day</div>
                    <Button size="sm">Select</Button>
                  </div>
                </div>
              </div>
            </div>
            <div
              className="bg-primary-foreground text-primary-background px-6 py-4 font-medium">
              Step 2: Choose Extras
            </div>
            <div className="p-6 space-y-6">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="bg-muted rounded-lg p-4 space-y-2">
                  <div className="font-medium">Insurance</div>
                  <div className="text-muted-foreground text-sm">
                    Protect your rental with our comprehensive insurance coverage.
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="font-medium">$10/day</div>
                    <Checkbox />
                  </div>
                </div>
                <div className="bg-muted rounded-lg p-4 space-y-2">
                  <div className="font-medium">GPS</div>
                  <div className="text-muted-foreground text-sm">
                    Never get lost with our built-in GPS navigation system.
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="font-medium">$5/day</div>
                    <Checkbox />
                  </div>
                </div>
                <div className="bg-muted rounded-lg p-4 space-y-2">
                  <div className="font-medium">Child Seat</div>
                  <div className="text-muted-foreground text-sm">
                    Ensure your little one's safety with our child seat rental.
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="font-medium">$8/day</div>
                    <Checkbox />
                  </div>
                </div>
              </div>
            </div>
            <div
              className="bg-primary-foreground text-primary-background px-6 py-4 font-medium">Step 3: Payment</div>
            <div className="p-6 space-y-6">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="pickup-location">Pickup Location</Label>
                  <Select id="pickup-location">
                    <SelectTrigger>
                      <SelectValue placeholder="Select pickup location" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="location1">Location 1</SelectItem>
                      <SelectItem value="location2">Location 2</SelectItem>
                      <SelectItem value="location3">Location 3</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label htmlFor="dropoff-location">Drop-off Location</Label>
                  <Select id="dropoff-location">
                    <SelectTrigger>
                      <SelectValue placeholder="Select drop-off location" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="location1">Location 1</SelectItem>
                      <SelectItem value="location2">Location 2</SelectItem>
                      <SelectItem value="location3">Location 3</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label htmlFor="pickup-date">Pickup Date</Label>
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        id="pickup-date"
                        variant="outline"
                        className="w-full justify-start text-left font-normal">
                        <CalendarDaysIcon className="mr-1 h-4 w-4 -translate-x-1" />
                        Select pickup date
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0" align="start">
                      <Calendar initialFocus mode="single" />
                    </PopoverContent>
                  </Popover>
                </div>
                <div>
                  <Label htmlFor="dropoff-date">Drop-off Date</Label>
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        id="dropoff-date"
                        variant="outline"
                        className="w-full justify-start text-left font-normal">
                        <CalendarDaysIcon className="mr-1 h-4 w-4 -translate-x-1" />
                        Select drop-off date
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0" align="start">
                      <Calendar initialFocus mode="single" />
                    </PopoverContent>
                  </Popover>
                </div>
              </div>
              <div className="bg-muted rounded-lg p-4 space-y-4">
                <div className="flex items-center justify-between">
                  <div>Car Rental</div>
                  <div className="font-medium">$50/day</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Insurance</div>
                  <div className="font-medium">$10/day</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>GPS</div>
                  <div className="font-medium">$5/day</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Child Seat</div>
                  <div className="font-medium">$8/day</div>
                </div>
                <Separator />
                <div className="flex items-center justify-between">
                  <div className="font-medium">Total</div>
                  <div className="font-medium">$73/day</div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="md:col-span-4 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Booking Summary</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div>
                  <div className="font-medium">Car</div>
                  <div>Toyota Camry</div>
                </div>
                <div>
                  <div className="font-medium">Pickup</div>
                  <div>Location 1</div>
                  <div>2023-06-01</div>
                </div>
                <div>
                  <div className="font-medium">Drop-off</div>
                  <div>Location 2</div>
                  <div>2023-06-08</div>
                </div>
                <div>
                  <div className="font-medium">Extras</div>
                  <div>Insurance, GPS</div>
                </div>
                <div className="font-medium">Total: $511</div>
              </div>
            </CardContent>
          </Card>
          <div className="flex justify-between">
            <Button variant="outline">Go Back</Button>
            <Button>Continue</Button>
          </div>
        </div>
      </div>
    </div>)
  );
}

function CalendarDaysIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>)
  );
}
