/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/iMTPg6sUKu8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Arimo } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Separator } from "@/components/ui/separator"

export function Payment_Page() {
  return (
    (<div className="w-full max-w-4xl mx-auto p-6 sm:p-8 md:p-10">
      <div className="grid md:grid-cols-2 gap-8">
        <div>
          <div className="mb-6">
            <h1 className="text-3xl font-bold">Complete your booking</h1>
            <p className="text-muted-foreground">Enter your payment details to finalize your car rental.</p>
          </div>
          <div className="space-y-4">
            <Card>
              <CardHeader>
                <CardTitle>Payment Method</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 gap-4">
                  <Button
                    variant="outline"
                    className="flex flex-col items-center justify-center gap-2 p-4 rounded-lg hover:bg-muted">
                    <CreditCardIcon className="w-8 h-8" />
                    <span>Credit Card</span>
                  </Button>
                  <Button
                    variant="outline"
                    className="flex flex-col items-center justify-center gap-2 p-4 rounded-lg hover:bg-muted">
                    <WalletIcon className="w-8 h-8" />
                    <span>PayPal</span>
                  </Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Credit Card</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="card-number">Card Number</Label>
                    <Input id="card-number" placeholder="1234 5678 9012 3456" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="card-expiry">Expiry Date</Label>
                    <Input id="card-expiry" placeholder="MM/YY" />
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="card-name">Name on Card</Label>
                    <Input id="card-name" placeholder="John Doe" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="card-cvc">CVC</Label>
                    <Input id="card-cvc" placeholder="123" />
                  </div>
                </div>
              </CardContent>
            </Card>
            <div className="flex items-center gap-2">
              <LockIcon className="w-5 h-5 text-primary" />
              <span className="text-sm text-muted-foreground">Your payment is secured with 256-bit encryption.</span>
            </div>
          </div>
        </div>
        <div>
          <div className="mb-6">
            <h2 className="text-2xl font-bold">Booking Summary</h2>
            <p className="text-muted-foreground">Review the details of your car rental before completing payment.</p>
          </div>
          <Card>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-lg font-medium">Toyota Camry</h3>
                  <p className="text-muted-foreground">Compact Sedan</p>
                </div>
                <div className="text-right">
                  <p className="text-lg font-medium">$50/day</p>
                  <p className="text-muted-foreground">+ taxes and fees</p>
                </div>
              </div>
              <Separator />
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-muted-foreground">Rental Duration</p>
                  <p>3 days</p>
                </div>
                <div className="text-right">
                  <p className="text-muted-foreground">Total</p>
                  <p className="text-2xl font-bold">$150</p>
                </div>
              </div>
              <Separator />
              <div className="flex items-center gap-2">
                <Input type="text" placeholder="Enter coupon code" className="flex-1" />
                <Button variant="outline">Apply</Button>
              </div>
            </CardContent>
          </Card>
          <div className="mt-6">
            <div className="mb-2" />
            <div className="flex items-center justify-between">
              <span className="text-sm text-muted-foreground">Step 3 of 4: Payment</span>
              <div className="flex items-center gap-2">
                <ShieldCheckIcon className="w-5 h-5 text-primary" />
                <span className="text-sm text-muted-foreground">Secure payment</span>
              </div>
            </div>
          </div>
          <Button type="submit" className="w-full mt-6">
            Complete Payment
          </Button>
        </div>
      </div>
    </div>)
  );
}

function CreditCardIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="14" x="2" y="5" rx="2" />
      <line x1="2" x2="22" y1="10" y2="10" />
    </svg>)
  );
}


function LockIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>)
  );
}


function ShieldCheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
      <path d="m9 12 2 2 4-4" />
    </svg>)
  );
}


function WalletIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1" />
      <path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4" />
    </svg>)
  );
}
