/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/uNO1yi99BRu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Switch } from "@/components/ui/switch"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Slider } from "@/components/ui/slider"

export function Settings3() {
  return (
    (<div className="w-full max-w-4xl mx-auto px-4 md:px-6 py-12">
      <h1 className="text-3xl font-bold mb-8">Settings</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div>
          <h2 className="text-2xl font-bold mb-4">Personal Information</h2>
          <Card>
            <CardContent className="space-y-4">
              <div className="grid gap-2">
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Enter your name" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" type="email" placeholder="Enter your email" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="phone">Phone</Label>
                <Input id="phone" type="tel" placeholder="Enter your phone number" />
              </div>
            </CardContent>
            <CardFooter>
              <Button className="ml-auto">Save Changes</Button>
            </CardFooter>
          </Card>
        </div>
        <div>
          <h2 className="text-2xl font-bold mb-4">Password Management</h2>
          <Card>
            <CardContent className="space-y-4">
              <div className="grid gap-2">
                <Label htmlFor="current-password">Current Password</Label>
                <Input
                  id="current-password"
                  type="password"
                  placeholder="Enter your current password" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="new-password">New Password</Label>
                <Input id="new-password" type="password" placeholder="Enter your new password" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="confirm-password">Confirm Password</Label>
                <Input
                  id="confirm-password"
                  type="password"
                  placeholder="Confirm your new password" />
              </div>
            </CardContent>
            <CardFooter>
              <Button className="ml-auto">Change Password</Button>
            </CardFooter>
          </Card>
        </div>
        <div>
          <h2 className="text-2xl font-bold mb-4">Notification Preferences</h2>
          <Card>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium">Email Notifications</p>
                  <p className="text-sm text-muted-foreground">Receive updates and offers via email</p>
                </div>
                <Switch id="email-notifications" aria-label="Email Notifications" />
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium">Push Notifications</p>
                  <p className="text-sm text-muted-foreground">Receive real-time updates and alerts</p>
                </div>
                <Switch id="push-notifications" aria-label="Push Notifications" />
              </div>
            </CardContent>
          </Card>
        </div>
        <div>
          <h2 className="text-2xl font-bold mb-4">Language</h2>
          <Card>
            <CardContent className="space-y-4">
              <div className="grid gap-2">
                <Label htmlFor="language">Select Language</Label>
                <Select id="language">
                  <SelectTrigger>
                    <SelectValue placeholder="Select language" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="en">English</SelectItem>
                    <SelectItem value="es">Español</SelectItem>
                    <SelectItem value="fr">Français</SelectItem>
                    <SelectItem value="de">Deutsch</SelectItem>
                    <SelectItem value="zh">中文</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </CardContent>
          </Card>
        </div>
        <div>
          <h2 className="text-2xl font-bold mb-4">Accessibility</h2>
          <Card>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium">Text Size</p>
                  <p className="text-sm text-muted-foreground">Adjust the text size for better readability</p>
                </div>
                <Slider
                  id="text-size"
                  min={12}
                  max={20}
                  step={2}
                  defaultValue={[16]}
                  aria-label="Text Size" />
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium">Color Contrast</p>
                  <p className="text-sm text-muted-foreground">Adjust the color contrast for better visibility</p>
                </div>
                <Slider
                  id="color-contrast"
                  min={1}
                  max={5}
                  step={1}
                  defaultValue={[3]}
                  aria-label="Color Contrast" />
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium">Screen Reader</p>
                  <p className="text-sm text-muted-foreground">Enable screen reader support</p>
                </div>
                <Switch id="screen-reader" aria-label="Screen Reader" />
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium">Keyboard Navigation</p>
                  <p className="text-sm text-muted-foreground">Enable keyboard-only navigation</p>
                </div>
                <Switch id="keyboard-navigation" aria-label="Keyboard Navigation" />
              </div>
            </CardContent>
          </Card>
        </div>
        <div>
          <h2 className="text-2xl font-bold mb-4">Membership Rewards</h2>
          <Card>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium">Rewards Points</p>
                  <p className="text-sm text-muted-foreground">You have 1,250 points</p>
                </div>
                <Button variant="outline">Manage Account</Button>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium">Membership Level</p>
                  <p className="text-sm text-muted-foreground">Gold</p>
                </div>
                <Button variant="outline">View Benefits</Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
      <div className="flex justify-end mt-8">
        <Button variant="outline" className="mr-4">
          Cancel
        </Button>
        <Button>Save Changes</Button>
      </div>
    </div>)
  );
}
